$kind: http-request
name: Update Task Order
method: PATCH
url: '{{baseUrl}}/tasks/{{taskId}}/order'
order: 2000
headers:
  - key: Authorization
    value: 'Bearer {{accessToken}}'
  - key: Content-Type
    value: application/json
pathVariables:
  - key: taskId
    value: '{{taskId}}'
body:
  type: json
  content: |-
    {
      "order": 0
    }
